#=================================
# Starting image
# https://hub.docker.com/r/budtmo/docker-android-x86-10.0
#=================================
FROM budtmo/docker-android-x86-10.0:latest

MAINTAINER antiylia

USER root

#=======================
# Gopy apk file into container
#=======================
COPY yandex_weather_v6.5.12.apk app/yandex_weather_v6.5.12.apk