#=================================
# Starting image
# https://hub.docker.com/r/budtmo/docker-android-x86-10.0
#=================================
FROM budtmo/docker-android-x86-10.0:latest

MAINTAINER antiylia

USER root

#=======================
# Gopy apk file into container
#=======================
COPY ru.yandex.weatherplugin_6.5.12_9341.apk ru.yandex.weatherplugin_6.5.12_9341.apk